# src/data_ingestion/readers/tntp_flow_reader.py

"""
TNTP Flow Reader
================

This module reads and normalizes observed or assigned link-flow files in a
TNTP-like format.

Project context
---------------
In the AADT / traffic assignment pipeline, the flow file provides link-level
traffic volumes. These volumes can represent:

- observed traffic counts used as ground truth;
- assigned link flows generated by a traffic assignment procedure;
- partially observed AADT values used to train or evaluate neural network models.

The normalized flow table later becomes part of the canonical link table and is
used to build:

- flow target vectors;
- observed-flow masks;
- link-level training losses;
- validation and diagnostic reports.

This reader is intentionally limited to data ingestion. It does not merge flows
with the network table, build graphs, compute routes, create tensors, or save
training artifacts. Those responsibilities belong to downstream builders,
adapters and artifact builders.

Expected input
--------------
A TNTP-like flow file may contain columns such as:

    From    To    Volume
    1       2     350.0
    2       3     410.5

or year-specific volume columns:

    from_node    to_node    Volume_2022    Volume_2023
    1            2          350.0          360.0
    2            3          NaN            410.5

The reader is tolerant to common aliases:
- "From", "from", "init_node", "origin" -> "from_node"
- "To", "to", "term_node", "destination" -> "to_node"
- "Volume", "volume", "flow", "assigned_flow" -> canonical selected volume column
- "Cost", "cost", "travel_time" -> "cost"

Output
------
The main output is a FlowReadResult containing:
- flow_df: normalized pandas DataFrame;
- metadata: dictionary with file path, selected volume column, number of links,
  number of observed links and volume statistics.

Design principles
-----------------
- Do only one thing: read and normalize link-flow data.
- Avoid hard-coded project paths.
- Preserve useful extra columns.
- Keep missing volume values as NaN so downstream builders can create proper
  observed-flow masks.
- Return metadata useful for validation and reproducibility.
"""

from __future__ import annotations

from dataclasses import dataclass
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import pandas as pd


logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class FlowReadResult:
    """
    Container returned by TNTPFlowReader.

    Attributes
    ----------
    flow_df : pd.DataFrame
        Normalized link-flow table.

    metadata : Dict[str, Any]
        Metadata describing the parsing result, including source file,
        selected volume column, number of records and basic volume statistics.
    """

    flow_df: pd.DataFrame
    metadata: Dict[str, Any]


class TNTPFlowReader:
    """
    Read and normalize a TNTP-like flow file.

    Parameters
    ----------
    path : Union[str, Path]
        Path to the flow file.

    volume_year : Optional[int], default=None
        Year used to select a year-specific volume column such as
        "Volume_2022". If None, the reader tries to select a generic volume
        column.

    volume_column : Optional[str], default=None
        Explicit volume column to use. If provided, it takes priority over
        volume_year.

    strict : bool, default=True
        If True, missing required columns or missing volume columns raise errors.

    preserve_extra_columns : bool, default=True
        If True, non-standard columns are kept in the output DataFrame.

    Required normalized columns
    ---------------------------
    - from_node
    - to_node

    Canonical output columns
    ------------------------
    - from_node
    - to_node
    - volume
    - cost, if available
    """

    REQUIRED_COLUMNS = {"from_node", "to_node"}

    CANONICAL_ORDER = [
        "from_node",
        "to_node",
        "volume",
        "cost",
    ]

    COLUMN_ALIASES = {
        "from": "from_node",
        "from_node": "from_node",
        "init_node": "from_node",
        "origin": "from_node",
        "u": "from_node",

        "to": "to_node",
        "to_node": "to_node",
        "term_node": "to_node",
        "destination": "to_node",
        "v": "to_node",

        "cost": "cost",
        "travel_time": "cost",
        "time": "cost",
    }

    VOLUME_CANDIDATES = [
        "volume",
        "flow",
        "assigned_flow",
        "aadt",
        "count",
        "traffic_count",
    ]

    COMMENT_PREFIXES = ("#", "//", "~")

    def __init__(
        self,
        path: Union[str, Path],
        volume_year: Optional[int] = None,
        volume_column: Optional[str] = None,
        strict: bool = True,
        preserve_extra_columns: bool = True,
    ) -> None:
        self.path = Path(path).resolve(strict=False)
        self.volume_year = volume_year
        self.volume_column = volume_column
        self.strict = bool(strict)
        self.preserve_extra_columns = bool(preserve_extra_columns)

        if not self.path.exists():
            raise FileNotFoundError(f"Flow file not found: {self.path}")

    def read(self) -> FlowReadResult:
        """
        Read, normalize and validate the flow file.

        Returns
        -------
        FlowReadResult
            Object containing the normalized flow DataFrame and metadata.

        Raises
        ------
        FileNotFoundError
            If the flow file does not exist.

        ValueError
            If required columns are missing or no valid flow rows are found.
        """

        logger.info("Reading TNTP flow file: %s", self.path)

        raw_df = self._read_raw_dataframe()
        flow_df = self._normalize_column_names(raw_df)

        selected_volume_column = self._select_volume_column(flow_df)
        flow_df = self._create_canonical_volume_column(
            flow_df=flow_df,
            selected_volume_column=selected_volume_column,
        )

        flow_df = self._normalize_dtypes(flow_df)
        flow_df = self._order_columns(flow_df)
        self._validate(flow_df)

        metadata = self._build_metadata(
            flow_df=flow_df,
            selected_volume_column=selected_volume_column,
            raw_columns=raw_df.columns.tolist(),
        )

        logger.info(
            "Flow file loaded successfully | records=%d | observed_volumes=%d | selected_volume_column=%s",
            len(flow_df),
            metadata["num_observed_volumes"],
            selected_volume_column,
        )

        return FlowReadResult(
            flow_df=flow_df,
            metadata=metadata,
        )

    def _read_raw_dataframe(self) -> pd.DataFrame:
        """
        Read the flow file into a raw DataFrame.

        The method assumes whitespace-separated TNTP-like files. Comment lines
        are ignored when possible.

        Returns
        -------
        pd.DataFrame
            Raw parsed DataFrame.
        """

        # Detect separator: check if first non-comment line contains '\t'
        sep = r"\s+"
        try:
            with self.path.open("r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    stripped = line.strip()
                    if not stripped or stripped.startswith(self.COMMENT_PREFIXES):
                        continue
                    if "\t" in line:
                        sep = "\t"
                    break
        except Exception as exc:
            logger.warning(
                "Failed to detect separator for flow file %s, falling back to default: %s",
                self.path,
                exc,
            )

        try:
            df = pd.read_csv(
                self.path,
                sep=sep,
                comment="#",
                engine="python",
            )
        except pd.errors.EmptyDataError as exc:
            raise ValueError(f"Flow file is empty: {self.path}") from exc

        # Remove semicolons that may appear in column names or cell values.
        df.columns = [str(col).strip().replace(";", "") for col in df.columns]

        for column in df.columns:
            if df[column].dtype == object:
                df[column] = (
                    df[column]
                    .astype(str)
                    .str.strip()
                    .str.replace(";", "", regex=False)
                )

        if df.empty:
            raise ValueError(f"No flow records found in file: {self.path}")

        return df

    def _normalize_column_names(self, flow_df: pd.DataFrame) -> pd.DataFrame:
        """
        Normalize known column names to the project canonical schema.

        Parameters
        ----------
        flow_df : pd.DataFrame
            Raw flow table.

        Returns
        -------
        pd.DataFrame
            Flow table with normalized column names where applicable.
        """

        rename_map = {}

        for column in flow_df.columns:
            key = str(column).strip().lower()
            rename_map[column] = self.COLUMN_ALIASES.get(key, column)

        df = flow_df.rename(columns=rename_map).copy()

        # If two input aliases map to the same canonical name, keep the first one.
        df = df.loc[:, ~df.columns.duplicated()].copy()

        return df

    def _select_volume_column(self, flow_df: pd.DataFrame) -> Optional[str]:
        """
        Select which input column should be used as the canonical volume column.

        Selection priority
        ------------------
        1. Explicit volume_column argument.
        2. volume_year="all": average all volume-like columns row-wise.
        3. volume_year=<year>: select one volume-like column ending in <year>.
        4. Generic candidates such as "volume", "flow", "aadt".

        Important
        ---------
        When multiple volume-like columns exist, the reader does not silently
        select the last one. The desired year must be configured through YAML,
        or volume_year must be set to "all".

        Parameters
        ----------
        flow_df : pd.DataFrame
            Flow table with normalized endpoint columns.

        Returns
        -------
        Optional[str]
            Selected volume column name. Returns None only when strict=False and
            no suitable volume column is found.
        """

        columns = list(flow_df.columns)
        lower_to_original = {str(col).lower(): col for col in columns}

        if self.volume_column is not None:
            if str(self.volume_column).lower() == "all":
                raise ValueError(
                    "volume_column='all' is not supported. Use volume_year='all' instead."
                )

            if self.volume_column in flow_df.columns:
                return self.volume_column

            lower_name = str(self.volume_column).lower()

            if lower_name in lower_to_original:
                return lower_to_original[lower_name]

            raise ValueError(
                f"Explicit volume column '{self.volume_column}' was not found. "
                f"Available columns: {columns}"
            )

        volume_like_columns = self._find_volume_like_columns(columns)

        is_active_year = self.volume_year not in (None, False, 0, "0", "False", "false", "")
        if is_active_year:
            volume_year = str(self.volume_year).strip().lower()

            if volume_year == "all":
                if not volume_like_columns:
                    if self.strict:
                        raise ValueError(
                            "volume_year='all' was requested, but no volume-like columns "
                            f"were found. Available columns: {columns}"
                        )
                    return None
                return volume_like_columns

            year_suffix = f"{volume_year}"
            year_matches = [
                col
                for col in volume_like_columns
                if str(col).strip().lower().endswith(year_suffix)
            ]

            if len(year_matches) == 1:
                return year_matches[0]

            if len(year_matches) > 1:
                raise ValueError(
                    f"volume_year={self.volume_year!r} matched multiple volume-like columns: "
                    f"{year_matches}. Use volume_column to disambiguate."
                )

            raise ValueError(
                f"volume_year={self.volume_year!r} did not match any volume-like column "
                f"ending in '{year_suffix}'. Volume-like columns found: {volume_like_columns}. "
                f"Available columns: {columns}"
            )

        for candidate in self.VOLUME_CANDIDATES:
            if candidate in lower_to_original:
                return lower_to_original[candidate]

        if len(volume_like_columns) == 1:
            return volume_like_columns[0]

        if len(volume_like_columns) > 1:
            raise ValueError(
                "Multiple volume-like columns were found, but neither volume_year nor "
                "volume_column was configured. Set readers.flows.volume_year to a year "
                "such as 2022, or to 'all' to average all volume-like columns. "
                f"Volume-like columns found: {volume_like_columns}"
            )

        if self.strict:
            raise ValueError(
                "No volume column could be identified in flow file. "
                f"Available columns: {columns}"
            )

        logger.warning(
            "No volume column could be identified. Creating canonical 'volume' column with NaN."
        )

        return None
    
    def _find_volume_like_columns(self, columns: List[Any]) -> List[Any]:
        """
        Return columns that can reasonably represent traffic volume values.

        A column is volume-like if its lower-case name is exactly one of the
        configured volume candidates, starts with one of those candidates plus
        an underscore, or contains the word "volume".
        """

        volume_like_columns: List[Any] = []

        for column in columns:
            name = str(column).strip().lower()

            is_candidate = name in self.VOLUME_CANDIDATES
            has_candidate_prefix = any(
                name.startswith(f"{candidate}_")
                for candidate in self.VOLUME_CANDIDATES
            )
            contains_volume = "volume" in name

            if is_candidate or has_candidate_prefix or contains_volume:
                volume_like_columns.append(column)

        return volume_like_columns

    def _create_canonical_volume_column(
        self,
        flow_df: pd.DataFrame,
        selected_volume_column: Optional[str],
    ) -> pd.DataFrame:
        """
        Create the canonical 'volume' column while preserving the original source.

        Missing values are intentionally kept as NaN. Downstream target builders
        should use these NaNs to create observed-flow masks.

        Parameters
        ----------
        flow_df : pd.DataFrame
            Flow table.

        selected_volume_column : Optional[str]
            Selected source column for volume.

        Returns
        -------
        pd.DataFrame
            Flow table with canonical volume column.
        """

        df = flow_df.copy()

        if selected_volume_column is None:
            df["volume"] = pd.NA
            return df

        df["volume"] = pd.to_numeric(
            df[selected_volume_column],
            errors="coerce",
        )

        return df

    def _normalize_dtypes(self, flow_df: pd.DataFrame) -> pd.DataFrame:
        """
        Convert core flow columns to stable data types.

        Parameters
        ----------
        flow_df : pd.DataFrame
            Flow table with canonical columns.

        Returns
        -------
        pd.DataFrame
            Flow table with normalized data types.
        """

        df = flow_df.copy()

        df["from_node"] = pd.to_numeric(df["from_node"], errors="coerce")
        df["to_node"] = pd.to_numeric(df["to_node"], errors="coerce")

        before = len(df)
        df = df.dropna(subset=["from_node", "to_node"])
        dropped = before - len(df)

        if dropped > 0:
            logger.warning(
                "Dropped %d flow rows because from_node or to_node could not be parsed.",
                dropped,
            )

        df["from_node"] = df["from_node"].astype(int)
        df["to_node"] = df["to_node"].astype(int)

        if "volume" in df.columns:
            df["volume"] = pd.to_numeric(df["volume"], errors="coerce")

        if "cost" in df.columns:
            df["cost"] = pd.to_numeric(df["cost"], errors="coerce")

        return df

    def _order_columns(self, flow_df: pd.DataFrame) -> pd.DataFrame:
        """
        Reorder columns so canonical flow fields appear first.

        Parameters
        ----------
        flow_df : pd.DataFrame
            Normalized flow table.

        Returns
        -------
        pd.DataFrame
            Reordered flow table.
        """

        canonical_present = [
            column
            for column in self.CANONICAL_ORDER
            if column in flow_df.columns
        ]

        if not self.preserve_extra_columns:
            return flow_df[canonical_present].copy()

        extra_columns = [
            column
            for column in flow_df.columns
            if column not in canonical_present
        ]

        return flow_df[canonical_present + extra_columns].copy()

    def _validate(self, flow_df: pd.DataFrame) -> None:
        """
        Validate the normalized flow table.

        This validation is intentionally limited to reader-level checks. Link
        consistency against the network table should be performed later by the
        link table builder or artifact validator.

        Parameters
        ----------
        flow_df : pd.DataFrame
            Normalized flow table.

        Raises
        ------
        ValueError
            If required endpoint columns are missing or invalid.
        """

        missing_columns = self.REQUIRED_COLUMNS - set(flow_df.columns)

        if missing_columns:
            raise ValueError(
                "Normalized flow table is missing required columns: "
                f"{sorted(missing_columns)}"
            )

        if flow_df.empty:
            raise ValueError("Normalized flow table is empty.")

        if flow_df[["from_node", "to_node"]].isna().any().any():
            raise ValueError("Missing values found in flow endpoint columns.")

        if "volume" not in flow_df.columns:
            raise ValueError("Normalized flow table does not contain canonical 'volume' column.")

        if (flow_df["volume"].dropna() < 0).any():
            raise ValueError("Flow table contains negative volume values.")

        duplicated_links = flow_df[["from_node", "to_node"]].duplicated(keep=False)

        if duplicated_links.any():
            duplicated_count = int(duplicated_links.sum())

            logger.warning(
                "Flow table contains %d duplicated directed link records. "
                "Downstream link table builder should decide how to aggregate or reject them.",
                duplicated_count,
            )

    def _build_metadata(
        self,
        flow_df: pd.DataFrame,
        selected_volume_column: Optional[str],
        raw_columns: List[str],
    ) -> Dict[str, Any]:
        """
        Build metadata describing the loaded flow file.

        Parameters
        ----------
        flow_df : pd.DataFrame
            Normalized flow table.

        selected_volume_column : Optional[str]
            Source column selected as volume.

        raw_columns : List[str]
            Original columns read from the file.

        Returns
        -------
        Dict[str, Any]
            Reader metadata.
        """

        observed_mask = flow_df["volume"].notna()
        observed_volume = flow_df.loc[observed_mask, "volume"]

        metadata: Dict[str, Any] = {
            "source_file": str(self.path),
            "raw_columns": raw_columns,
            "columns": flow_df.columns.tolist(),
            "selected_volume_column": selected_volume_column,
            "volume_year": self.volume_year,
            "num_records": int(len(flow_df)),
            "num_observed_volumes": int(observed_mask.sum()),
            "num_missing_volumes": int((~observed_mask).sum()),
            "observed_volume_share": (
                float(observed_mask.mean()) if len(flow_df) > 0 else 0.0
            ),
        }

        if len(observed_volume) > 0:
            metadata.update(
                {
                    "total_observed_volume": float(observed_volume.sum()),
                    "mean_observed_volume": float(observed_volume.mean()),
                    "min_observed_volume": float(observed_volume.min()),
                    "max_observed_volume": float(observed_volume.max()),
                }
            )
        else:
            metadata.update(
                {
                    "total_observed_volume": 0.0,
                    "mean_observed_volume": None,
                    "min_observed_volume": None,
                    "max_observed_volume": None,
                }
            )

        if "cost" in flow_df.columns:
            observed_cost = flow_df["cost"].dropna()

            metadata["num_observed_costs"] = int(len(observed_cost))

            if len(observed_cost) > 0:
                metadata["mean_observed_cost"] = float(observed_cost.mean())
                metadata["min_observed_cost"] = float(observed_cost.min())
                metadata["max_observed_cost"] = float(observed_cost.max())

        return metadata


def read_tntp_flows(
    path: Union[str, Path],
    volume_year: Optional[int] = None,
    volume_column: Optional[str] = None,
    strict: bool = True,
    preserve_extra_columns: bool = True,
) -> FlowReadResult:
    """
    Convenience function to read a TNTP-like flow file.

    Parameters
    ----------
    path : Union[str, Path]
        Path to the flow file.

    volume_year : Optional[int], default=None
        Year used to select a year-specific volume column.

    volume_column : Optional[str], default=None
        Explicit source column to use as canonical volume.

    strict : bool, default=True
        Whether to use strict validation behavior.

    preserve_extra_columns : bool, default=True
        Whether to keep non-standard columns in the output DataFrame.

    Returns
    -------
    FlowReadResult
        Normalized flow DataFrame and metadata.
    """

    reader = TNTPFlowReader(
        path=path,
        volume_year=volume_year,
        volume_column=volume_column,
        strict=strict,
        preserve_extra_columns=preserve_extra_columns,
    )

    return reader.read()