# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize  # minimizar el MSE
    study_name: traffic_assignment_optimization
    storage: null  #
    n_trials: 20   # Número total de experimentos a correr
    n_jobs: 1

    # PARAMETER SEARCH SPACE
    params:

      # --- 1. ARQUITECTURA  ---

      model.hidden_dim: choice(64, 128, 256)
      model.feature_dim: choice(32, 64)
      # Número de estructuras en el GraphMatcher
      model.num_structures: int(interval(3, 10))
      # Dropout
      model.dropout: interval(0.0, 0.5)

      # --- 2. ENTRENAMIENTO ---

      training.lr: tag(log, interval(0.0001, 0.1))

      training.weight_decay: interval(1e-6, 1e-3)

      # --- 3. FÍSICA Y PÉRDIDA  ---
      # model.loss_weights.w_reg: interval(0.001, 0.1)
      # model.loss_weights.w_od: interval(0.1, 5.0)