# configs/data_handling/data_preprocessing/preprocessing_from_pkl.yaml
# =============================================================================

# NOTA: Eliminamos 'dataset: Linköping' porque ya está definido globalmente.

# Usamos las variables globales:
# ${paths.data_raw} -> viene de config.yaml
# ${dataset.name}   -> viene de configs/dataset/Linköping.yaml (o el que elijas)

pickle_data_path: ${paths.data_raw}/${dataset.name}/pickle/${dataset.name}_Pickle_Data.pkl