# configs/training/training.yaml
# =============================================================================

# Input Routes para el entrenamiento
# El código de entrenamiento espera encontrar esto en cfg.training.input_routes
input_routes:
  # Usamos ${data.base_path} que viene de Linköping.yaml
  graph: ${data.base_path}/${data.graph_file}
  route_cache: ${data.base_path}/${data.routing_cache_file}
  od_matrix: ${data.base_path}/${data.od_matrix_file}
  link_df: ${data.base_path}/${data.link_data_file}

# Hiperparámetros del Entrenamiento (Optimizador, Loops, etc.)
epochs: 900
batch_size: 1
lr: 4.0e-3
weight_decay: 1e-3

# Warmup policy: controla si se utiliza warmup y cuántas épocas dura
warmup:
  enabled: false # true | false
  epochs: 50

# Configuración del Optimizador
optimizer: "adamw" # 'adam' | 'sgd' | 'adamw'

# Scheduler (Control de tasa de aprendizaje)
scheduler: "reduce_on_plateau"
grad_clip_norm: 0.5
scheduler_params:
  factor: 0.5
  patience: 10
  min_lr: 1e-6

# Early Stopping (Parada temprana si no mejora)
early_stopping:
  enabled: false
  patience: 20
  min_delta: 0.0001

# Configuración de Hardware
device: "cuda"  # 'cuda', 'cpu', o 'auto'

metrics_on_training: true # Calcular métricas durante el entrenamiento

# Prescaling strategy for inputs: 'standard' | 'capacity' | 'max'
scaling_strategy: max # standard | capacity | max

# Validación
val_frequency: 5

# Tuning

tuning: null # 'datadriven' | 'sue' | null (null para no tuning)
k_folds: 1  # Número de folds para cross-validation
