
name: Synthetic06
description: A synthetic small scenario.
seed: 56

#%%

NodeParameters:
  Quantity:
    TAZ: 20
    AUX: 5
    INTERSECTION: 40

  Coordinates:
    x_min: 0
    x_max: 100
    y_min: 0
    y_max: 100

  Types:
    # Types only define the split between zone and non-zone node labels.
    Zones:
      - TAZ
      - AUX
    NonZones:
      - INTERSECTION
    
  Tabular:
    Columns:
      - "node_id"
      - "x"
      - "y"
      - "type"
      - "class"

#%%
    
DemandParameters:
  Num_Days: 10
  Start_Date: "2022-01-01" # YYYY-MM-DD optional, solo para referencia
  Time_Interval: H # H: hourly, 15m: 15 minutes, etc.
  Accept_IntraZonal_Demand: true

  Magnitude:
    min_trips_od: 0
    max_trips_od: 20

  Profile:
    {
    "00:00": 0.3, "01:00": 0.2, "02:00": 0.1, "03:00": 0.1,
    "04:00": 0.3, "05:00": 0.5, "06:00": 0.8, "07:00": 1.0,
    "08:00": 1.4, "09:00": 1.2, "10:00": 1.0, "11:00": 0.8,
    "12:00": 0.9, "13:00": 1.0, "14:00": 1.0, "15:00": 1.2,
    "16:00": 1.3, "17:00": 1.7, "18:00": 1.5, "19:00": 0.8,
    "20:00": 0.7, "21:00": 0.6, "22:00": 0.3, "23:00": 0.3
    }

  Tabular:
    Columns: ["origin_id", "destination_id", "departure_time", "day", "num_trips"]

#%%

NetworkParameters:
  Tabular:
    Assignment_Columns:
      - link_id # Necesario para mergear con flows_df después de la asignación y obtener los atributos de los enlaces en el DataFrame de flujos
      - assigned_flow
      - travel_time
      - v/c

    Base_Columns:
      - link_id
      - reverse_link_id
      - init_node
      - term_node
      - capacity_per_lane
      - lanes
      - total_capacity
      - effective_capacity
      - length
      - free_flow_time
      - b
      - power
      - speed
      - vdf
      - toll
      - link_type

    Columns: ${oc.select:NetworkParameters.Tabular.Base_Columns}

  Catalogues:
    Network:
    # Definición de tipos de enlaces (link types) y sus atributos asociados
      1: 
        description: "Highways"
        is_connector: false
        capacity: 1800
        lanes: 3
        toll: 0  # Assuming toll is a binary attribute (0 for no toll, 1 for toll)
        allowed_vdfs: [1]  # List of VDF IDs compatible with this type
      2:
        description: "Arterials"
        is_connector: false
        capacity: 900
        lanes: 2
        toll: 0
        allowed_vdfs: [1, 2] # Can have multiple VDF profiles
      3:
        description: "Collectors"
        is_connector: false
        capacity: 300
        lanes: 1
        toll: 0
        allowed_vdfs: [3]
      99:
        description: "Connectors (Auxiliary)"
        is_connector: true
        capacity: 9999
        lanes: 1
        toll: 0
        allowed_vdfs: [99]

    VDF:
      1:
        description: "BPR standard"
        b: 0.15
        power: 4.0
        speed_limit: 60.0
      2:
        description: "BPR modified for arterials"
        b: 0.20
        power: 5.0
        speed_limit: 45.0
      3:
        description: "BPR modified for collectors"
        b: 0.25
        power: 6.0
        speed_limit: 30.0
      99:
        description: "Free flow (for connectors)"
        b: 0.0
        power: 0.0
        speed_limit: 9999.0
  
#%%

RouteParameters:
  K_paths: 10
  Weight: "free_flow_time" # Attribute used to calculate shortest paths

  # Constraints for route generation
  allow_duplicates: false   # Within the K-routes, a route can be appear multiple times.
  allow_loops: false        # A route can pass multiple times through the same node, but not through the same link
  allow_auto_routes: true   # A route can start and end in the same node, creating a loop. This is useful for intra-zonal trips.

 
AssignmentParameters:
  Capacity_Adjustment_Factors:
    # Capacities are given vehicles/hour, but we are dealing with daily flows
    # therefore we need to artificially increase the capacities to avoid oversaturation in the assignment
    from_hourly_to_daily: 12

  # Paradigma/Algoritmo de Asignación: "SUE" (Stochastic User Equilibrium), "UE" (User Equilibrium)
  Paradigm: "SUE" # SUE | UE
  
  # Método de convergencia: "MSA" (Method of Successive Averages), "frank_wolfe" (Frank-Wolfe algorithm)
  Method: "MSA" # MSA | frank_wolfe

  Max_Iterations: 10
  ConvergenceParameters:

    # Distancia L1 total (suma de diferencias absolutas en todas la red) en vehículos
    equilibrium_l1_threshold: 20.0
    # Máximo desajuste absolute que se permite en un solo enlace (vehículos)
    max_absolute_gap_threshold: 2.0
    # Máximo desajuste relativo que se permite en un solo enlace (vehículos)
    max_relative_gap_threshold: 5e-4
    # Flujos mínimo para calcular el gap relativo (evita división por cero)
    min_flow_for_relative_gap: 1.0

  # Parámetros específicos para el método de asignación seleccionado
  SUE_Parameters:
    # Parámetro de aleatoriedad para SUE, entre 0 (comportamiento completamente aleatorio) y +inf (comportamiento completamente determinista, equivalente a UE)
    theta: 2.0 # 0.5 (moderatey sthochastic) | 2.0 (more deterministic) | 1000.0 (almost deterministic)

    step_size: 0.5

  MSA:
    msa_step_rule: "1_over_n"

  Tabular:
    Columns: ["From", "To", "Volume"]

  AssignmentControl:
    DemandBalance:
      absolute_tolerance: 1.0
      relative_tolerance: 1e-4

    ZoneNodeBalance:
      absolute_tolerance: 1.0
      relative_tolerance: 1e-4

    NonZoneNodeBalance:
      absolute_tolerance: 1.0
      relative_tolerance: 1e-4

VisualizationParameters:
  Nodes:

    Label_Size: 12
    Label_Color: "black"

    TAZ:
      Size: 300
      Color: "e74c3c" # Red
      Show_Label: true
      Marker: "s" # Square marker for TAZ
      Label: "TAZ"

    AUX:
      Size: 200
      Color: "2ecc71" # Green
      Show_Label: true
      Marker: "^" # Triangle marker for AUX
      Label: "AUX"

    INTERSECTIONS:
      Size: 100
      Color: "3498db" # Blue
      Show_Label: true
      Marker: "o" # Circle marker for Intersections
      Label: "Intersection"

  Edges:
    Width: 2
    Color: "gray"
    Show_Label: true
    Label_Size: 10
    Label_Color: "black"

  VDF_Curves: # TODO: Esto es un placeholder, la visualización de curvas VDF puede ser más compleja y requerir su propia sección
    Show: true
    Color: "orange"
    Width: 2
    Show_Label: true
    Label_Size: 10
    Label_Color: "black"
