# @package _global_
# configs/sampling/sampling.yaml

# Definimos input_routes a nivel global para que las interpolaciones funcionen
input_routes:
  # Usamos la ruta base que ya cargó Linköping.yaml
  general_route: ${data.base_path}

  # Rutas derivadas
  graph_route: ${input_routes.general_route}/${data.dataset}_graph.pkl
  od_matrix_route: ${input_routes.general_route}/${data.dataset}_od_matrix.npz
  link_data_route: ${input_routes.general_route}/${data.dataset}_link_data.parquet

# Parámetros de sampling (quedarán en cfg.sampling)
sampling:
  flow_rate: 0.8
  od_rate: 1.0
  sampling_basis: link_wise_based
  output_dir: outputs/masks
  output_filename: sampled_flow_mask.npy
  # Estrategia por defecto dentro del bloque sampling
  strategy: spatial_LHS

# Estrategias disponibles (nivel global o referenciadas por el engine)
sampling_strategies_routes:
  random_sampling: src.components.sampling.strategies.random_sampler:RandomStrategy
  spatial_LHS: src.components.sampling.strategies.spatial_LHS:SpatialLHSStrategy